Added php contact form functionality
However, I'm recieving an error in XAMPP:

"Warning: require_once(/Applications/XAMPP/xamppfiles/htdocslibs/contact-form/phpmailer/phpmailer.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/polyfen/libs/contact-form/functions.php on line 4

Fatal error: require_once(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocslibs/contact-form/phpmailer/phpmailer.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/polyfen/libs/contact-form/functions.php on line 4"

I believe the error might be caused by XAMPP's config. Maybe, we should test it on our live server.